### ISSUE TITLE
ServiceStack 5 is out.

### ISSUE THREAD

**Issue by AdrianCohea** [wwwlicious/servicestack-configuration-consul#1]
It looks like ServiceStack 5 just came out. I haven't looked through the codebase yet, but I wonder if it's as simple as just recompiling this against SS 5 and removing the "strictly less than" constraint in the nuspec file.

Thoughts?

**Comment by wwwlicious** [comment]
@AdrianCohea I don't there are any breaking changes but will need to find some time to do it. PR's are always welcome, otherwise I'll try and get to it sometime in the next week or so.

**Comment by wwwlicious** [comment]
version [4.0.11](https://www.nuget.org/packages/ServiceStack.Configuration.Consul/4.0.11) with support for Servicestack v5 is now available on nuget.
